cookie:
  secure: true

cors:
  allowed-origin: ${CORS_ALLOWED_ORIGIN}

app:
  base-url: ${APP_BASE_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      public:
        info: false
        prometheus: false
  endpoint:
    health:
      show-details: never
      show-components: never
